export const PRODUCTION_URL = 'http://portal.cs1.io/';
export const DEVELOPMENT_URL = 'http://portal.cs1.io/';
export const DOMAIN_URL = `${DEVELOPMENT_URL}`;
export const LOGIN_URL = `${DOMAIN_URL}authenticate_admin/`;
export const PORTFOLIO_URL = `${DOMAIN_URL}api/portfolio/actions/`;
export const ACCOUNTS_INFO_URL = `${DOMAIN_URL}api/accounts/info/?active=false`;
export const ACCOUNTS_KPI_URL = `${DOMAIN_URL}api/accounts/kpi/?active=false`;
export const ACCOUNTS_USERS_KPI_URL = `${DOMAIN_URL}api/accounts/users_kpi/?active=false`;
export const ACTIONS_URL = `${DOMAIN_URL}api/actions/`;
export const TOKEN = 'JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZlOTY2NjdhLTY3NGItNDg1ZC1hNTcxLWEzYjJjMTMxNmM5MiIsInVzZXJfaWQiOiJmZTk2NjY3YS02NzRiLTQ4NWQtYTU3MS1hM2IyYzEzMTZjOTIiLCJzZXNzaW9uX2lkIjoicmFuZG9tIHNlc3Npb24iLCJyb2xlIjpbIkFETSIsIkRBIiwiQ1NNIiwiQ1NPIiwiQ1NMIl0sImhvc3RfbmFtZSI6InBvcnRhbC5jczEuaW8iLCJleHAiOjE1MDQxODE0NzV9.Ovpg00DzUaQsPXTXYxsJ3MqNbeZttBeKbi73C3HwsuI';
